FROM python:3.7.4
WORKDIR /myproject/new_blog


COPY ./requirements.txt ./
RUN pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple

COPY . ./

CMD ["gunicorn", "start:app", "-c", "./gunicorn.conf.py"]
